{
 "title": "Flask K8s Monitoring",
 "tags": [
  "flask",
  "k8s",
  "prometheus"
 ],
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "sum(app_requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "In-progress Requests",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "sum(app_inprogress_requests)", "legendFormat": "In-progress" }
   ]
  },
  {
   "title": "Pod CPU Usage (millicores)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (pod) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}