apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'flask'
        static_configs:
          - targets: ['flask-k8s-service.default.svc.cluster.local:80']
