apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-k8s
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      containers:
      - name: flask
        image: flask-k8s-app:latest  # Built inside Minikube
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
